steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/test-boilerplate', '.']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'test-boilerplate'
  - '--image'
  - 'gcr.io/$PROJECT_ID/test-boilerplate:$COMMIT_SHA'
  - '--region'
  - 'us-west1-b'
  - '--platform'
  - 'managed'
images:
- 'gcr.io/$PROJECT_ID/test-boilerplate'